### ISSUE TITLE
Overriding `ActiveModel::Model.model_name` in `DfE::Wizard::Step` has a side-effect on i18n keys.

### ISSUE THREAD

**Issue by steventux** [DFE-Digital/dfe-wizard#1]
`DfE::Wizard::Step` overrides the class method [`ActiveModel::Model.model_name`](https://api.rubyonrails.org/classes/ActiveModel/Naming.html#method-i-model_name), stripping it of matches on _"Step"_ and demodularizing it. This means that i18n keys for wizard steps are more likely to collide as they are no longer namespaced.

eg. `SomeNamespace::SomeWizard::SuccessStep.model_name.i18n_key` will be `:success` if the step class inherits from `DfE::Wizard::Step`
The `ActiveModel::Model.model_name.i18n_key` return value would be `:"some_namespace/some_wizard/success_step"` which is less likely to collide with other i18n keys.

~I can only see one reference to the overridden method here: https://github.com/DFE-Digital/dfe-wizard/blob/main/lib/dfe/wizard/step.rb#L28 and I think it's possible to avoid overriding `ActiveModel::Model.model_name` and still achieve the same stripped back step name without this side-effect. I'm wary that there might be other implications or side-effects in doing this.~

[update] It's possible to retain the namespacing in the i18n key and produce the same minimal model name, see example in comment below.

WDYT @tomas-stefano ? Happy to raise a PR if what I've said here makes sense.

**Comment by steventux** [comment]
FWIW something like:

```ruby
module DfE
  module Wizard
    class Step
...
      def self.model_name
        activemodel_model_name = super
        step_model_name = ActiveModel::Name.new(self, nil, formatted_name.demodulize)
        step_model_name.i18n_key = activemodel_model_name.i18n_key
        step_model_name
      end
...

```

Would preserve the I18n key and produce the same model name in other places like form fields, params etc.

**Comment by tomas-stefano** [comment]
Thank you for raising!

Yes, I saw this when I was doing the second wizard using this library in Publish.  

Yes, I agree. your idea does makes sense to me. About opening a PR, yes please :).
